### ISSUE TITLE
Options for usage with Github.com and hosting the app

### ISSUE THREAD

**Issue by cj-taylor** [github/rally#107]
Howdy, folks! 

Congrats on releasing another helpful [integration](https://github.blog/2020-08-18-introducing-the-rally-github-integration/). I'm very interested as someone utilizing both tools in scope with home-grown solutions this could replace. Thank you for sharing this with the community!

For context, I currently run on repositories a custom GitHub Action that checks URL/Format of Rally references in Pull Request Description fields to encourage population of the Rally Connection tabs.

## re: github.com support

The release and docs make this seem to be largely targeting GitHub Enterprise Self-hosted. However, being backed by a `probot` app, it does look like the setup could be altered a bit to make that work with Github.com. If Github.com (or GitHub Enterprise Cloud) isn't supported yet, are there plans to?

## re: Hosting options

For alternative hosting options, is there a viable/known path of hosting GitHub Probot or GitHub Apps via GitHub Actions? Could there be a path of utilizing `repository_dispatch` events?

Cheers, 
@cj-taylor

**Comment by primetheus** [comment]
@cj-taylor thanks for opening this up! You are correct, since this is built on Probot it will work seamlessly on GitHub.com already. All you need to do is comment out the `GHE_HOST=` line in the `.env` file and it will default to GitHub.com. We specifically targeted GHES because there [is an existing integration](https://rally1.rallydev.com/apps/github-app/home) created and hosted by Broadcom, but you can very easily host this for GHEC. Does that answer your question?

**Comment by primetheus** [comment]
>For alternative hosting options, is there a viable/known path of hosting GitHub Probot or GitHub Apps via GitHub Actions? Could there be a path of utilizing `repository_dispatch` events?

That is certainly a possibility... this can be adapted to be an Action and trigger from pull requests there, or `repository_dispatch` events. Long-term that will probably be the more common way of using this, since Actions for GHES is coming soon. I'll add a roadmap item to track that effort.
